<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-11-30 17:43

$extensionPath = t3lib_extMgm::extPath('ics_layar_service');
return array(
	'tx_icslayarservice_pager' => $extensionPath . 'Classes/class.tx_icslayarservice_pager.php',
	'tx_icslayarservice_service' => $extensionPath . 'Classes/class.tx_icslayarservice_service.php',
	'tx_icslayarservice_source' => $extensionPath . 'Classes/class.tx_icslayarservice_source.php',
	'tx_icslayarservice_transformation' => $extensionPath . 'Classes/class.tx_icslayarservice_transformation.php',
);
?>